/*
 *     This file is part of ToroDB.
 *
 *     ToroDB is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General PublicSchema License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     ToroDB is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General PublicSchema License for more details.
 *
 *     You should have received a copy of the GNU Affero General PublicSchema License
 *     along with ToroDB. If not, see <http://www.gnu.org/licenses/>.
 *
 *     Copyright (c) 2014, 8Kdata Technology
 *     
 */

package com.torodb.torod.db.backends.meta.routines;

import com.torodb.torod.db.backends.meta.IndexStorage;
import com.torodb.torod.db.backends.meta.TorodbSchema;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReserveDocIds extends org.jooq.impl.AbstractRoutine<java.lang.Integer> {

	private static final long serialVersionUID = -566845238;

	/**
	 * The parameter <code>torodb.reserve_value_type_id.RETURN_VALUE</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.INTEGER);

	/**
	 * The parameter <code>torodb.reserve_value_type_id.col_schema</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> COL_SCHEMA = createParameter("col_schema", org.jooq.impl.SQLDataType.VARCHAR);

	/**
	 * The parameter <code>torodb.reserve_value_type_id.increment</code>.
	 */
	public static final org.jooq.Parameter<java.lang.Integer> INCREMENT = createParameter("increment", org.jooq.impl.SQLDataType.INTEGER);

	/**
	 * Create a new routine call instance
	 */
	public ReserveDocIds() {
		super("reserve_doc_ids", TorodbSchema.TORODB, org.jooq.impl.SQLDataType.INTEGER);

		setReturnParameter(RETURN_VALUE);
		addInParameter(COL_SCHEMA);
		addInParameter(INCREMENT);
	}

	/**
	 * Set the <code>col_schema</code> parameter IN value to the routine
	 */
	public void setColSchema(IndexStorage.CollectionSchema colSchema) {
		setValue(ReserveDocIds.COL_SCHEMA, colSchema.getName());
	}

	/**
	 * Set the <code>col_schema</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setColSchema(org.jooq.Field<java.lang.String> field) {
		setField(COL_SCHEMA, field);
	}

	/**
	 * Set the <code>increment</code> parameter IN value to the routine
	 */
	public void setIncrement(java.lang.Integer value) {
		setValue(ReserveDocIds.INCREMENT, value);
	}

	/**
	 * Set the <code>increment</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setIncrement(org.jooq.Field<java.lang.Integer> field) {
		setField(INCREMENT, field);
	}
}
