/*
 * ToroDB
 * Copyright © 2014 8Kdata Technology (www.8kdata.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package com.torodb.backend.udt;

import com.torodb.backend.meta.TorodbSchema;
import com.torodb.backend.udt.record.Decimal128Record;
import com.torodb.backend.udt.record.MongoTimestampRecord;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.UDTImpl;
import org.jooq.util.postgres.PostgresDataType;

import java.math.BigDecimal;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = {"http://www.jooq.org", "3.4.1"},
    comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Decimal128UDT extends UDTImpl<Decimal128Record> {

  public static final String IDENTIFIER = "decimal_128";

  private static final long serialVersionUID = -552117608;

  /**
   * The singleton instance of <code>torodb.mongo_timestamp</code>
   */
  public static final Decimal128UDT DECIMAL_128_UDT = new Decimal128UDT();

  /**
   * The class holding records for this type
   */
  @Override
  public Class<Decimal128Record> getRecordType() {
    return Decimal128Record.class;
  }

  /**
   * The attribute <code>torodb.decimal_128.upper</code>.
   */
  public static final org.jooq.UDTField<Decimal128Record, BigDecimal> VALUE = createField("value",
          PostgresDataType.NUMERIC, DECIMAL_128_UDT);
  /**
   * The attribute <code>torodb.mongo_timestap.upper</code>.
   */
  public static final org.jooq.UDTField<Decimal128Record, Boolean> IS_INFINITY = createField("is_infinity",
          SQLDataType.BOOLEAN, DECIMAL_128_UDT);
  /**
   * The attribute <code>torodb.mongo_timestap.upper</code>.
   */
  public static final org.jooq.UDTField<Decimal128Record, Boolean> IS_NaN = createField("is_nan",
          SQLDataType.BOOLEAN, DECIMAL_128_UDT);
  /**
   * The attribute <code>torodb.mongo_timestap.upper</code>.
   */
  public static final org.jooq.UDTField<Decimal128Record, Boolean> IS_NEGATIVE_ZERO = createField("is_negative_zero",
          SQLDataType.BOOLEAN, DECIMAL_128_UDT);



  /**
   * No further instances allowed
   */
  private Decimal128UDT() {
    super(IDENTIFIER, TorodbSchema.TORODB);

    // Initialise data type
    getDataType();
  }

  @Override
  public boolean equals(Object that) {
    return super.equals(that);
  }

  @Override
  public int hashCode() {
    return super.hashCode();
  }

}
